name: terminator-cu117
channels:
  - defaults
  - https://conda.anaconda.org/rdkit
  - conda-forge
dependencies:
  - python=3.10
  - rdkit==2022.03.3
  - pip>=19.1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu117
      - --find-links https://pytorch-geometric.com/whl/torch-1.13.1+cu117.html
      - torch==1.13.1+cu117
      - transformers==4.29.2
      - torch==1.13.1+cu117
      - tqdm
      - numpy
      - modlamp>=4.3.0
      - selfies==1.0.4
      - psutil
      - flake8==3.8.4
      - mypy==0.800
      - pytest==6.1.1
      - pytest-cov==2.10.1
      - black==20.8b1
      - sphinx==3.4.3
      - sphinx-autodoc-typehints==1.11.1
      - better-apidoc==0.3.1
      - sphinx_rtd_theme==0.5.1
      - myst-parser==0.13.3
      - flask==1.1.2
      - flask_login==0.5.0
      - -e .
